### PR TITLE
Added awesome badge and contribution.md

### PR DESCRIPTION
**Pull request by othreecodes**

### CODE REVIEW

**Comment by othreecodes** [comment]
@olucurious :point_up_2:

**Comment by olucurious** [comment]
Thanks a lot for the PR, but I noticed contributing.md is referencing another file code-of-conduct.md which actually doesn't exist. 
And then, waiting for 30 days sounds like a lot to me, the list hasn't gathered a lot of momentum, so we shouldn't make it hard too hard for people to contribute.

Thanks again

**Comment by othreecodes** [comment]
How may days do you propose. I was about to open an Issue for the code-code-of-conduct.md

**Comment by olucurious** [comment]
@othreecodes I'll actually say 24 hours for now

**Comment by olucurious** [comment]
@othreecodes Gracias

**Pull request merged**
