### PR TITLE
Substituted solar system repo for a new one

### PR DESCRIPTION
**Pull request by xavipedrals**
It's nearly the same project as ARSolarPlay, but this one was built in Swift 4 instead of Objective C. Everything is in English and there are no Chinese comments in the code. The code is divided in easy to navigate short files instead of one 1000+ lines file.

### CODE REVIEW

**Comment by olucurious** [comment]
Hi @xavipedrals I just got a report from @miliPolo that your submission is really a conversion and replacement of his project from Objc to Swift 4 without any credit reference to the original project, I will hereby revert the changes in this PR until the appropriate credit is given.

**Comment by xavipedrals** [comment]
Hi, for sure. I added this on my project repo, after the project description:

This project was based on another project written in ObjC by [Alex Yang](https://github.com/milipolo), checkout the repo [here](https://github.com/miliPolo/ARSolarPlay).

Is it okay?

**Comment by miliPolo** [comment]
I think I can provide a swift4 version later, thank you

**Comment by miliPolo** [comment]
Actually it has nothing to do with the code, the key is that you didn't notice me, and replace my code, your behavior is equivalent to as long as someone else's code is not good enough, you can replace it.

**Comment by miliPolo** [comment]
Sorry, I just saw the latest dialogue. I understand that the problem seems to be solved.Thank you. @xavipedrals @olucurious

**Pull request merged**
